apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retail-store-services
  namespace: monitoring
  labels:
    app: retail-store
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: retail-store
  namespaceSelector:
    matchNames:
      - retail-store
  endpoints:
    - port: http
      interval: 30s
      path: /actuator/prometheus
      scheme: http
